### ISSUE TITLE
BackupPC 4.4.1 ?

### ISSUE THREAD

**Issue by sebruant** [yurtesen/zabbix_backuppc#4]
Hello, where you get BackupPC 4.4.1 ? Latest is 4.4.0 for years.

**Comment by yurtesen** [comment]
After 4.4.0 release. I made a PR to backuppc 
https://github.com/backuppc/backuppc/pull/391
But they did not seem to have released new version.
You need to download the master manually to be able to use the latest BackupPC.
Alternatively you could ask backuppc developers to make a release

**Comment by sandrobordacchini** [comment]
Hello @yurtesen , thank you for your great work.
I am using backuppc installed with the standard package distributed with Debian Bullseye.
The package version is 4.4.0-3.
I don't think your PR is in it ( https://sources.debian.org/src/backuppc/4.4.0-3/ ).
Since your PR involves only Metrics.pm file, do you think it is safe to try to just upgrade the single file and not all the code...?

**Comment by yurtesen** [comment]
Hello @sandrobordacchini 
I believe it should be safe. But I opened an issue with the BackupPC project also. Feel free to comment your opinions also there:
https://github.com/backuppc/backuppc/issues/481
It might be good if they make a release.

**Comment by sandrobordacchini** [comment]
Yep, i confirm, i replaced the file and i get a well-formatted json (still have to check the figures, but i will when i will hook it up to a zabbix).
I had to manually install **JSON::XS** via **cpan** though, actually that prevented also the old metrics to work...

I think that's more of a debian packaging (deps) issue though, like the missing depend from the **nmblookup** executable that makes backuppc service die.

I tried to write to the debian mantainers without success.
I'll drop a comment on your issue too.

**Comment by sandrobordacchini** [comment]
Hello @yurtesen 
Sorry to contact you after all this time.
I am still using the system with only Metrics.pm updated to the master branch.
I am experiencing, on a few hosts, some "Size difference larger than 1GB" alarms.
Some are months old, some go off for a couple hours and then stop.

How can I investigate these alarms?
Do you have any hint?

Thanks a lot.

**Comment by sandrobordacchini** [comment]
I increased the threshold like you said, @yurtesen 
Thanks.
