### ISSUE TITLE
Cannot perform cURL request: Couldn't resolve host name.

### ISSUE THREAD

**Issue by giovanecoca** [yurtesen/zabbix_backuppc#7]
When i try configure, this message is shown: Cannot perform cURL request: Couldn't resolve host name.

Hostname or IP is correct.

Can you help me?

**Comment by giovanecoca** [comment]
> I suspect your zabbix agent is not able to resolve the host. Please check your logs.

I found the problem but I can't solve it.

My backuppc password has special characters like @ and # and Zabbix cannot handle these characters.

You know how?

**Comment by yurtesen** [comment]
You might need to encode special characters which can't be used with an URL. But alternatively, use password without special characters. 
See: https://stackoverflow.com/questions/22544219/how-do-i-use-special-characters-password-on-the-url-when-dealing-with-http-aut

**Comment by giovanecoca** [comment]
Its working. Tks :D
